version: '3.8'


services:
  chrome:
    image: selenium/standalone-firefox-debug:3.141.59
    hostname: chrome
    privileged: true
    shm_size: 2g
    ports:
      - 5900:5900
      - 4444:4444
      - 9515:9515
    environment:
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=